use_frameworks!

target 'WZPayment_Example' do
  pod 'WZPayment', :path => '../'

  pod 'WZNetworks', '~> 6.1.9' #网络
  pod 'WZRxExtension/DisposeBag', '~> 0.3.1' #RxDisposeBag
  pod 'WZProgressHUD', '~> 1.1.2' #加载框
  pod 'CleanJSON', '~> 1.0.9' #动态处理JSON问题
  pod 'CocoaDebug', '~> 1.7.7'
  target 'WZPayment_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 13.0
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
end
